services:
  app:
    image: node:22-alpine
    working_dir: /app
    ports:
      - 3000:3000
    env_file:
     - ".env"
    volumes:
      - ./:/app
    depends_on:
      - mongo
    command: ["npm", "run", "start"]
  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arthos
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=arthos
    volumes:
      - ./mongo_data:/data/db  # Map to a local 'mongo_data' folder
